# ----------------------------------
#
#             Jekyll Settings
#
# ----------------------------------

baseurl: /

title: Hello World
description: Foobar
markdown: kramdown
plugins:
  - jekyll-sitemap

# Don't forget trailing slash or it won't work on test server
# Uncommenting permalink messes up '404.html' for Github Pages
# permalink: :year/:title/

# Github Pages only runs in safe mode
safe: true

sass:
  # style: compressed
  # sass_dir: _sass

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page

# ----------------------------------
#
#             Customization
#
# ----------------------------------

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

# assets:
#   asset_path: /uploads/

opengraph: false

#------------------------------------------------------------
#
#  Excludes
#
#------------------------------------------------------------

exclude:
  - "*.lock"
  - "*.log"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Gemfile
  - LICENSE
  - README.md
  - bower_components
  - gulpfile.js
  - gulpfile.babel.js
  - modernizr-config.json
  - node_modules
  - package-lock.json
  - package.json


