---
title: Hello World
description: Foobar
markdown: kramdown
permalink: /posts/:title
exclude: ["bower_components", "node_modules", "config.rb", "gulpfile.js", "package.json","*.sublime-project", "*.sublime-workspace", "*.log", "css/_breakpoints", "LICENSE", "README.md"]

plugins:
  - jekyll-sitemap

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page

# Dependancies

sass:
  # style: compressed
  # sass_dir: _sass

# Assets
# assets:
  # asset_path: /assets/

# Custom

# Don't forget trailing slash or it won't work on test server
permalink: :year/:title/
exclude: ["Gemfile", "modernizr-config.json", "*.lock", "bower_components", "node_modules", "config.rb", "gulpfile.js", "package.json", "package-lock.json","*.sublime-project", "*.sublime-workspace", "*.log", "LICENSE", "README.md"]

# Build settings
markdown: kramdown
