title: Hello World
description: Foobar
markdown: kramdown
exclude: ["Gemfile", "modernizr-config.json", "*.lock", "bower_components", "node_modules", "gulpfile.js", "package.json", "package-lock.json","*.sublime-project", "*.sublime-workspace", "*.log", "LICENSE", "README.md"]

# Don't forget trailing slash or it won't work on test server
permalink: :year/:title/

plugins:
  - jekyll-sitemap

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page


sass:
  # style: compressed
  # sass_dir: _sass

# CUSTOM

opengraph: false

# Assets
# assets:
  # asset_path: assets/


